apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-org
  description: A collection of all Presidio Demo Org entities
spec:
  targets:
  - ./guest-org.yaml
  - ./main-org.yaml
  - ./appdev.yaml
  - ./devops.yaml
  - ./data.yaml
  - ./office-admin.yaml
