apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: appdev
  description: Application Development Team
  annotations:
    aws.amazon.com/cost-insights-tags: team=appdev
spec:
  type: team
  profile:
    displayName: AppDev
    email: appdev@example.com
    picture: https://api.dicebear.com/9.x/icons/svg?seed=Boo&background=transparent
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kavin
spec:
  profile:
    displayName: Kavin
    email: kavin@example.com
    picture: https://api.dicebear.com/7.x/initials/svg?seed=kg
  memberOf: [appdev]
