apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: office-admin
  description: Office Admin Team
  annotations:
    aws.amazon.com/cost-insights-tags: team=office-admin
spec:
  type: team
  profile:
    displayName: Office Admin
    email: office-admin@example.com
    picture: https://api.dicebear.com/9.x/icons/svg?seed=Boo&background=transparent
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Hari
spec:
  profile:
    displayName: Hari
    email: hari@example.com
    picture: https://api.dicebear.com/7.x/initials/svg?seed=HA
  memberOf: [office-admin]
